FROM node:16-alpine as build
WORKDIR /app

COPY package.json .
COPY yarn.lock .
RUN yarn
COPY . .

ARG OPEN_CAGE_API_KEY
ENV OPEN_CAGE_API_KEY=$OPEN_CAGE_API_KEY

ARG OPEN_WEATHER_KEY
ENV OPEN_WEATHER_KEY=$OPEN_WEATHER_KEY

RUN yarn build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html