version: "3"
services:
  charlie:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - OPEN_CAGE_API_KEY=c63386b4f77e46de817bdf94f552cddf
      - OPEN_WEATHER_KEY=772920597e4ec8f00de8d376dfb3f094
      - WATCHPACK_POLLING=true